/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.TransferenciaStockController;
import Modelo.DTO.ResultadoOperacionDTO;
import Modelo.DTO.ValidarCantidadAlmacenDTO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Area_Registrar_Transferencias extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Area_Registrar_Transferencias.class.getName());
    private int idUsuario;
    private TransferenciaStockController transferencia;
    public Area_Registrar_Transferencias(int idUsuario) {
        initComponents();
        this.idUsuario=idUsuario;
         this.transferencia = new TransferenciaStockController();
        setLocationRelativeTo(null);
        setTitle("Área para registrar transferencia de stock");
        LlenarComboBoxProductos();
        JTextField spinnerEditor = ((JSpinner.DefaultEditor) cantidadTrasladoSpinner.getEditor()).getTextField();
        spinnerEditor.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                cantidadTrasladoSpinnerKeyPressed(e); // Llama al método que ya tienes
            }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreProductoCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cantidadTrasladoSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        RealizarTrasladoBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CerrarSesionBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Área de transferencia de stock a tienda");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad a Trasladar:");

        NombreProductoCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NombreProductoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del Producto:");

        cantidadTrasladoSpinner.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidadTrasladoSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadTrasladoSpinnerKeyPressed(evt);
            }
        });

        TablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Producto", "Nombre", "Cantidad", "Unidad de Medida", "Subtotal en Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        RealizarTrasladoBtn.setText("Realizar Traslado");
        RealizarTrasladoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RealizarTrasladoBtn.addActionListener(this::RealizarTrasladoBtnActionPerformed);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Siempre tenga en cuenta la unidad de Medida");

        CerrarSesionBtn.setBackground(new java.awt.Color(214, 40, 40));
        CerrarSesionBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CerrarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Log out icon.png"))); // NOI18N
        CerrarSesionBtn.setText("Cerrar sesión");
        CerrarSesionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesionBtn.setVerifyInputWhenFocusTarget(false);
        CerrarSesionBtn.addActionListener(this::CerrarSesionBtnActionPerformed);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recuerde presionar Enter para registrar un Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(RealizarTrasladoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadTrasladoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(NombreProductoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarSesionBtn)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(810, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(NombreProductoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CerrarSesionBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidadTrasladoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(RealizarTrasladoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel3)
                    .addContainerGap(674, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarTrasladoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarTrasladoBtnActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaProductos.getModel();
        int productos=modelo.getRowCount();
        if(productos==0){
            JOptionPane.showMessageDialog(null, "No hay ningún producto por registrar");
            return;
        }
        Map<Integer,double[]> productosYDatos=new LinkedHashMap<>();
        for(int i=0;i<productos;i++){
            int idProducto=(int) modelo.getValueAt(i,0);
            int cantidad=(int) modelo.getValueAt(i,2);
            double subtotal=(double) modelo.getValueAt(i,4);
            productosYDatos.put(idProducto, new double[]{cantidad,subtotal});
        }
         ResultadoOperacionDTO resultado = transferencia.registrarTransferenciaCompleta(idUsuario, productosYDatos);
         if ("OK".equals(resultado.getEstado())) {
            JOptionPane.showMessageDialog(null, resultado.getMensaje());
            modelo.setRowCount(0); 
         } else {
                JOptionPane.showMessageDialog(null, resultado.getMensaje());
         }
    }//GEN-LAST:event_RealizarTrasladoBtnActionPerformed
    private void LlenarComboBoxProductos(){
        NombreProductoCB.removeAllItems();
        List<String> productos=transferencia.ObtenerNombresProductos();
        for(String producto:productos){
            NombreProductoCB.addItem(producto);
        }
    }
    private void cantidadTrasladoSpinnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTrasladoSpinnerKeyPressed
        DefaultTableModel modelo = (DefaultTableModel) TablaProductos.getModel();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String nombreProducto=NombreProductoCB.getSelectedItem().toString();
            int cantidad=(int) cantidadTrasladoSpinner.getValue();
            ValidarCantidadAlmacenDTO resultado=transferencia.ValidarCantidadTrasladar(nombreProducto, cantidad);
            if(resultado.esExitoso()){
                modelo.addRow(new Object[]{
                    resultado.getIDProducto(),
                    resultado.getNombre(),
                    resultado.getCantidad(),
                    resultado.getUnidadMedida(),
                    resultado.getSubtotalStock()
                });
                cantidadTrasladoSpinner.setValue(1);
            }
            else {
                JOptionPane.showMessageDialog(null, resultado.getMensaje());
            }
        }
    }//GEN-LAST:event_cantidadTrasladoSpinnerKeyPressed

    private void CerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBtnActionPerformed
        int resultado=JOptionPane.showConfirmDialog(null,"Estás seguro de querer cerrar sesión?","Confirmación de cierre de sesión",JOptionPane.YES_NO_OPTION);
        if(resultado==0){
          this.dispose();
         new Login().setVisible(true); 
        }
    }//GEN-LAST:event_CerrarSesionBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesionBtn;
    private javax.swing.JComboBox<String> NombreProductoCB;
    private javax.swing.JButton RealizarTrasladoBtn;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JSpinner cantidadTrasladoSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
