/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


import Controlador.NotificacionesController;
import Modelo.DTO.ProductosBajoStockDTO;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ListaProductosBajoStock extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaProductosBajoStock.class.getName());
    private int idNotificacion;
    private NotificacionesController notificaciones;
    public ListaProductosBajoStock(java.awt.Window parent, Map<String, List<ProductosBajoStockDTO>> productosBajos,int idNotificacion) {
        super(parent,ModalityType.APPLICATION_MODAL);
        initComponents();
        cargarDatos(productosBajos);
        this.notificaciones=new NotificacionesController();
        setTitle("Lista de productos bajo Stock");
        int x = parent.getX() + (parent.getWidth() - getWidth()) / 2; // centrado horizontalmente
        int y = parent.getY() + parent.getHeight() - getHeight() - 10; // parte baja con margen de 10px
        setLocation(x, y);
        this.idNotificacion=idNotificacion;
    }
    private void cargarDatos(Map<String, List<ProductosBajoStockDTO>> productosBajos){
         for (Map.Entry<String, List<ProductosBajoStockDTO>> entry : productosBajos.entrySet()){
             lblTitulo.setText(entry.getKey());
             DefaultTableModel modelo=(DefaultTableModel) TablaPBS.getModel();
             for(ProductosBajoStockDTO producto:entry.getValue()){
                modelo.addRow(new Object[]{producto.getNombre(),producto.getStockActual(),producto.getStockMinimo()});
             }
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPBS = new javax.swing.JTable();
        cerrarListaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Título");

        TablaPBS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre_Producto", "Stock_Actual", "Stock_Minimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPBS);

        cerrarListaBtn.setText("Cerrar Lista");
        cerrarListaBtn.addActionListener(this::cerrarListaBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(cerrarListaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarListaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarListaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarListaBtnActionPerformed
        if(notificaciones.NotificacionLeida(idNotificacion)){
            JOptionPane.showMessageDialog(null,"Notificación marcada como leída");
            this.dispose();
        }
    }//GEN-LAST:event_cerrarListaBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPBS;
    private javax.swing.JButton cerrarListaBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
