/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.NotificacionesController;
import Modelo.DTO.ProductosBajoStockDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Date;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class NotificacionStockAlmacen extends javax.swing.JPanel {
    private Integer IDMensaje;
    private String Titulo;
    private Date Date;
    private String Mensaje;
    private NotificacionesController notificaciones;
    public NotificacionStockAlmacen(Integer IDMensaje,String Titulo,Date Date,String Mensaje) {
        initComponents();
        setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
        setMaximumSize(new Dimension(570, 78));
        setPreferredSize(new Dimension(570, 78));
        this.IDMensaje=IDMensaje;
        this.Titulo=Titulo;
        this.Date=Date;
        this.notificaciones=new NotificacionesController();
        this.Mensaje=Mensaje;
        LlenarNotificacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarBoton = new javax.swing.JLabel();
        Titulolb = new javax.swing.JLabel();
        IDMensajelb = new javax.swing.JLabel();
        Fechalb = new javax.swing.JLabel();
        Mensajelb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 63));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        cerrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_button.jpg"))); // NOI18N
        cerrarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarBotonMouseClicked(evt);
            }
        });

        Titulolb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Titulolb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulolb.setText("Título");
        Titulolb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        IDMensajelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDMensajelb.setText("ID_Mensaje");
        IDMensajelb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Fechalb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fechalb.setText("Día");
        Fechalb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Mensajelb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mensajelb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Mensajelb.setText("Mensaje");
        Mensajelb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mensajelb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(IDMensajelb, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Titulolb, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fechalb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarBoton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titulolb)
                            .addComponent(IDMensajelb)
                            .addComponent(Fechalb)))
                    .addComponent(cerrarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mensajelb, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void LlenarNotificacion(){
        Titulolb.setText(Titulo);
        Mensajelb.setText(Mensaje);
        IDMensajelb.setText("Mensaje #"+IDMensaje.toString());
        Fechalb.setText(Date.toString());
    }
    private void cerrarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBotonMouseClicked
        this.setVisible(false);
        java.awt.Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        if (ventanaPadre instanceof Area_Notificaciones) {
            ((Area_Notificaciones) ventanaPadre).verificarNotificaciones();
        }
    }//GEN-LAST:event_cerrarBotonMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Map<String,List<ProductosBajoStockDTO>> productosBajos=notificaciones.mostrarListaProductos(IDMensaje);
        ListaProductosBajoStock dialog=new ListaProductosBajoStock(SwingUtilities.getWindowAncestor(this),productosBajos,IDMensaje);
        dialog.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fechalb;
    private javax.swing.JLabel IDMensajelb;
    private javax.swing.JLabel Mensajelb;
    private javax.swing.JLabel Titulolb;
    private javax.swing.JLabel cerrarBoton;
    // End of variables declaration//GEN-END:variables
}
